# Generated by Django 3.2.9 on 2021-11-18 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='etq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_name', models.CharField(blank=True, max_length=50, null=True)),
                ('etq_att', models.IntegerField(blank=True, default='0', null=True)),
                ('etq_add', models.IntegerField(blank=True, default='0', null=True)),
                ('forn', models.CharField(blank=True, max_length=50, null=True)),
                ('etq_rmv', models.IntegerField(blank=True, default='0', null=True)),
                ('rmv_user', models.CharField(blank=True, max_length=50, null=True)),
                ('rmv_dest', models.CharField(blank=True, max_length=50, null=True)),
                ('etq_min', models.IntegerField(blank=True, default='0', null=True)),
                ('last_buy', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
