# Generated by Django 3.2.9 on 2021-11-18 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easymngmnt', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='etq',
            new_name='Estoque',
        ),
    ]
