# Generated by Django 3.2.9 on 2021-11-19 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easymngmnt', '0003_estoque_categoria'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='forn',
            new_name='destino',
        ),
        migrations.RenameField(
            model_name='estoque',
            old_name='etq_add',
            new_name='diminuir_item',
        ),
        migrations.RenameField(
            model_name='estoque',
            old_name='etq_att',
            new_name='estoque_adicionar',
        ),
        migrations.RenameField(
            model_name='estoque',
            old_name='etq_min',
            new_name='estoque_atual',
        ),
        migrations.RenameField(
            model_name='estoque',
            old_name='etq_rmv',
            new_name='estoque_minimo',
        ),
        migrations.RenameField(
            model_name='estoque',
            old_name='prod_name',
            new_name='fornecedpr',
        ),
        migrations.RenameField(
            model_name='estoque',
            old_name='rmv_dest',
            new_name='nome',
        ),
        migrations.RenameField(
            model_name='estoque',
            old_name='rmv_user',
            new_name='remover_user',
        ),
    ]
