# Generated by Django 3.2.9 on 2021-11-20 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('easymngmnt', '0006_alter_estoque_estoque_atual'),
    ]

    operations = [
        migrations.CreateModel(
            name='categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='estoque',
            name='categoria',
            field=models.CharField(blank=True, choices=[('Consumível', 'Consumível'), ('Ferramenta', 'Ferramenta')], max_length=50, null=True),
        ),
    ]
