# Generated by Django 3.2.9 on 2021-11-20 03:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('easymngmnt', '0007_auto_20211120_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estoque',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='easymngmnt.categoria'),
        ),
    ]
