# Generated by Django 3.2.9 on 2021-11-20 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easymngmnt', '0010_estoque_recebido'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='recebido',
            new_name='recebi',
        ),
    ]
