# Generated by Django 3.2.9 on 2021-11-20 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easymngmnt', '0011_rename_recebido_estoque_recebi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='diminuir_item',
            new_name='entrega',
        ),
    ]
