# Generated by Django 3.2.9 on 2021-11-20 17:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('easymngmnt', '0012_rename_diminuir_item_estoque_entrega'),
    ]

    operations = [
        migrations.RenameField(
            model_name='estoque',
            old_name='estoque_minimo',
            new_name='aviso',
        ),
    ]
